version: '3'
services:
   jupyterlab:
      build:
         context: ./compose/jupyterlab
      user: root
      working_dir: /home/jovyan/work
      ports:
         - "8888:8888"
      volumes:
         - ".:/home/jovyan/work"
      environment:
         NB_UID: 1000
         GRANT_SUDO: "yes"
      command: start.sh jupyter lab --NotebookApp.token='' 
